# Generated by Django 5.0.6 on 2024-05-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, verbose_name='Gatunek')),
                ('jarski', models.BooleanField(default=False, help_text='Zaznacz, jeżeli treść jest nie odpowiednia dla Osoby wrażliwe', verbose_name='Tagi?')),
                ('książka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gatunek', to='BOOKS.books')),
            ],
        ),
        migrations.DeleteModel(
            name='Gatunek',
        ),
    ]
