# Generated by Django 5.0.6 on 2024-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKS', '0002_genre_delete_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='jarski',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeżeli treść jest nie odpowiednia dla Osoby wrażliwe', verbose_name='Tagi'),
        ),
    ]
